#!/usr/bin/env bash
# Regenerate the committed differential-test fixtures under fixtures/official/ from
# the Java reference. Requires:
#   scripts/fetch-reference.sh  (provides reference/test.beagle.vcf.gz + jars)
#   scripts/build-java.sh       (provides reference/beagle.local.jar)
# Golden outputs are produced with fixed determinism knobs so they are byte-for-byte
# reproducible and serve as the parity target for the Rust port.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REF="$ROOT/reference"
JAR="$REF/beagle.local.jar"
BREF_JAR="$REF/bref3.local.jar"
FIX="$ROOT/fixtures/official"
SEED=99999
THREADS=1
VER="27Feb25.75f"

for f in "$JAR" "$BREF_JAR" "$REF/test.beagle.vcf.gz"; do
  [ -f "$f" ] || { echo "ERROR: missing $f — run scripts/fetch-reference.sh && scripts/build-java.sh first." >&2; exit 1; }
done

mkdir -p "$FIX/inputs" "$FIX/golden"
tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
cd "$tmp"

# --- derive inputs exactly as the official run example does ---
cp "$REF/test.beagle.vcf.gz" test.$VER.vcf.gz
zcat test.$VER.vcf.gz | cut -f1-190 | tr '/' '|' | gzip > ref.$VER.vcf.gz
zcat test.$VER.vcf.gz | cut -f1-9,191-200 | gzip > target.$VER.vcf.gz
java -jar "$BREF_JAR" ref.$VER.vcf.gz > ref.$VER.bref3 2>/dev/null

# --- golden outputs (fixed seed + single thread) ---
java -jar "$JAR" gt=test.$VER.vcf.gz                              out=out.gt    nthreads=$THREADS seed=$SEED >/dev/null 2>&1
java -jar "$JAR" ref=ref.$VER.vcf.gz  gt=target.$VER.vcf.gz       out=out.ref   nthreads=$THREADS seed=$SEED >/dev/null 2>&1
java -jar "$JAR" ref=ref.$VER.bref3   gt=target.$VER.vcf.gz       out=out.bref3 nthreads=$THREADS seed=$SEED >/dev/null 2>&1

cp test.$VER.vcf.gz ref.$VER.vcf.gz target.$VER.vcf.gz ref.$VER.bref3 "$FIX/inputs/"
cp out.gt.vcf.gz out.ref.vcf.gz out.bref3.vcf.gz "$FIX/golden/"

# --- manifest with the exact commands + checksums ---
{
  echo "# Beagle $VER differential-test fixtures"
  echo
  echo "Generated by scripts/make-fixtures.sh. Determinism: nthreads=$THREADS seed=$SEED."
  echo "The golden outputs below are the byte-for-byte parity target for beagle-rs."
  echo
  echo '## inputs/'
  echo '- `test.'$VER'.vcf.gz`   — 1356 markers, 191 samples (1000G chr22 slice)'
  echo '- `ref.'$VER'.vcf.gz`    — 181 samples, phased (`/`→`|`); reference panel'
  echo '- `target.'$VER'.vcf.gz` — 10 samples; imputation target'
  echo '- `ref.'$VER'.bref3`     — `ref` panel in bref3 binary format'
  echo
  echo '## golden/ (produced by the Java reference)'
  echo '- `out.gt.vcf.gz`    = `beagle gt=test out=out.gt`'
  echo '- `out.ref.vcf.gz`   = `beagle ref=ref.vcf.gz gt=target out=out.ref`'
  echo '- `out.bref3.vcf.gz` = `beagle ref=ref.bref3 gt=target out=out.bref3`'
  echo
  echo '## sha256'
  echo '```'
  ( cd "$FIX" && sha256sum inputs/* golden/* )
  echo '```'
} > "$FIX/MANIFEST.md"

echo ">> fixtures written to $FIX"
( cd "$FIX" && sha256sum inputs/* golden/* )
