//! Cross-language parity for the `ints` package: the Rust port must reproduce, line
//! for line, the transcript emitted by the Java reference
//! (`tools/java/IntsParityDriver.java`, regenerated by `scripts/gen-ints-parity.sh`
//! into `fixtures/ints/parity.txt`). This proves the full port→verify loop on one
//! package, including byte-exact bit packing (the `packedwords` lines) and the
//! internal ordering of `IntIntMap` keys/values.

use beagle_rs::ints::{
    self, CharArray, IntArray, IntIntMap, IntList, PackedIntArray, UnsignedByteArray,
    WrappedIntArray,
};

const VALUE_SIZES: [i32; 14] = [1, 2, 3, 4, 5, 8, 15, 16, 17, 100, 256, 1000, 65536, 70000];

fn values(vs: i32) -> Vec<i32> {
    (0..50).map(|j| j % vs).collect()
}

/// Mirrors the driver's `getCsv` (no spaces).
fn get_csv(a: &dyn IntArray) -> String {
    (0..a.size())
        .map(|j| a.get(j).to_string())
        .collect::<Vec<_>>()
        .join(",")
}

/// Mirrors `java.util.Arrays.toString(int[])` (`[a, b, c]`).
fn arrays_to_string(a: &[i32]) -> String {
    let mut s = String::from("[");
    for (i, v) in a.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        s.push_str(&v.to_string());
    }
    s.push(']');
    s
}

fn transcript() -> String {
    let mut out = String::new();
    out.push_str("# ints parity transcript (Beagle 5.5 27Feb25.75f)\n");

    for &vs in &VALUE_SIZES {
        let v = values(vs);
        out.push_str(&format!(
            "packedCreate vs={} get={}\n",
            vs,
            get_csv(ints::packed_create(&v, vs).as_ref())
        ));
        out.push_str(&format!(
            "create vs={} get={}\n",
            vs,
            get_csv(ints::create(&v, vs).as_ref())
        ));
    }

    for &vs in &VALUE_SIZES {
        if vs <= 16 {
            let p = PackedIntArray::from_slice(&values(vs), vs);
            out.push_str(&format!(
                "packedwords vs={} ia={}\n",
                vs,
                arrays_to_string(p.words())
            ));
        }
    }

    let mut il = IntList::new();
    for j in 0..30 {
        il.add(j);
    }
    out.push_str(&format!("intlist toString={}\n", il));
    out.push_str(&format!(
        "intlist copyOf35={}\n",
        arrays_to_string(&il.copy_of(35))
    ));
    out.push_str(&format!(
        "intlist copyOfRange5_40={}\n",
        arrays_to_string(&il.copy_of_range(5, 40))
    ));
    il.sort();
    out.push_str(&format!("intlist sorted={}\n", il));
    out.push_str(&format!(
        "intlist bsearch13={} bsearch1000={}\n",
        il.binary_search(13),
        il.binary_search(1000)
    ));

    let mut m = IntIntMap::new(4);
    for i in 0..300 {
        let key = (i * 37) % 50;
        if i % 5 == 0 {
            m.remove(key);
        } else {
            m.put(key, i);
        }
    }
    out.push_str(&format!(
        "intintmap size={} keys={} values={}\n",
        m.size(),
        arrays_to_string(&m.keys()),
        arrays_to_string(&m.values())
    ));

    out.push_str(&format!(
        "ubyte={}\n",
        get_csv(&UnsignedByteArray::from_ints(&[0, 127, 255]))
    ));
    out.push_str(&format!(
        "char={}\n",
        get_csv(&CharArray::from_ints(&[0, 4660, 65535]))
    ));
    out.push_str(&format!(
        "wrapped={}\n",
        get_csv(&WrappedIntArray::from_slice(&[7, 8, 9]))
    ));

    out
}

#[test]
fn ints_parity_matches_java_reference() {
    let expected = include_str!("../../../fixtures/ints/parity.txt");
    let actual = transcript();
    assert_eq!(
        actual, expected,
        "Rust ints transcript diverged from the Java reference"
    );
}
